---
- name: Installing VSFTPD
  hosts: all
  vars_files:
    - vars
  tasks:
  - name: Installing VSFTPD
    yum:
      name: vsftpd
      state: latest
  - name: Starting VSFTPD Service
    service:
      name: vsftpd
      state: started
      enabled: true
  - name: Creating a user
    user:
      name: "{{ user }}"
      password: "{{ password | password_hash('sha512') }}"
