---
- name: Installing VSFTPD
  hosts: all
  tasks:
  - name: Installing VSFTPD
    yum:
      name: vsftpd
      state: latest
  - name: Starting VSFTPD Service
    service:
      name: vsftpd
      state: started
      enabled: true
